---
title: "Digital online patient informed consent for anesthesia before elective diagnostic procedures or surgery: Recent practice in children – here stands Europe (2021)"
output: html_document
---
```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tableone)
library(RColorBrewer)
library(scales)
library(lessR)



# library(ReporteRs)
# library(magrittr)
```

```{r Data import and cleaning}
survey_data <- read_csv("survey_data_no_other.csv")
survey_data_all_countries <- read_csv("survey_data_all_countries.csv")
survey_fragments <- read_csv("shiny_esaic/survey_fragments.csv")
# Responses eligible for analysis (country != "Other")
table(survey_data_all_countries$`Country where you work?` == "Other")
```

### Methods
```{r Profession distribution}
profession_table <- table(survey_data$Profession)
prop.table(profession_table)
```
```{r Gender distribution}
gender_table <- table(survey_data$Gender)
prop.table(gender_table)
```
```{r Expert level distribution}
expertise_table <- table(survey_data$`Your expert level`)
prop.table(expertise_table)
```
```{r Table 1: Profession and expert level distirbution stratified by gender}
# stratification by gender
catVars = "Gender"

contVars = c(
    "Profession",
    "Your expert level"
)
# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateTableOne(
        data = survey_data,
        vars = contVars,
        addOverall = FALSE,
        strata = catVars
    )

results_tbl <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)

# writing the table to excel
# write.xlsx(results_tbl,
#            file = "~/Desktop/R/Shiny/ESAIC-survey/ESAIC-KAI-survey-2021/master_data.xlsx",
#            sheetName = "demographics_paper_gender_fix", 
#            col.names = TRUE, 
#            row.names = TRUE, 
#            append = TRUE)
```
```{r Plot Specialty distribution separated by country}
survey_data_barchart <- survey_data %>% 
    select(c("Country where you work?", "Your expert level"))

colnames(survey_data_barchart) <- c("country", "expert.level")

# changing UK name so in can fit to mapdata
survey_data_barchart$country[survey_data_barchart$country == "United Kingdom (UK)"] <- "UK" 
survey_data_barchart$country[survey_data_barchart$country == "North Macedonia (formerly Macedonia)"] <- "Macedonia" 
survey_data_barchart$country[survey_data_barchart$country == "Bosnia and Herzegovina"] <- "B&H" 


# # nice but no fill 
# survey_data_barchart %>%
#     dplyr::filter(!is.na(expert.level)) %>% 
#     dplyr::filter(!is.na(country)) %>% 
#     count(country, sort = TRUE) %>%
#     mutate(country = fct_reorder(country, n)) %>% 
#     ggplot(aes(x = country, n)) +
#     geom_bar(stat ="identity") +
#     coord_flip() 

# stacked responses base on country
survey_data_barchart %>%
    dplyr::filter(!is.na(expert.level)) %>% 
    dplyr::filter(!is.na(country)) %>% 
    group_by(expert.level) %>% 
    count(country) %>%
    # mutate(country = fct_reorder(country, n)) %>% 
    ggplot(aes(x = reorder(country, +n, FUN = sum), n, fill = expert.level)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    theme(legend.position="top",
          axis.text.x = element_text(size = 20, vjust = 1.3),
          axis.text.y = element_text(size = 15),
          legend.title = element_blank(),
          axis.ticks = element_blank(),
          # axis.title.y = element_blank(),
          # axis.title.x = element_blank(),
          rect = element_blank(),
          legend.text = element_text(size=25),
          axis.title.x = element_text(size=20, vjust = 0.5)) +
    guides(fill = guide_legend("")) +
    labs(x = "",
         y = "Responses") +
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C", "#AF357E")) 
     # scale_fill_brewer(palette = "Set1")
    #scale_x_discrete(guide = guide_axis(n.dodge = 2))
```


### Results
```{r PIE When do you need to obtain Informed consent for elective surgery based on legal requirements?}
prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for simple procedures, low risk patients)."))
prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for complex procedures, higher risk patients)."))

# 24 h prior and 24 prior because of daily routine pooled together
simple_df <- data.frame(simple_complex = c(rep("simple", 3), rep("complex", 3)),
                        answer = rep(c("2 days or more", "24h or less", "Same day"), 2),
                        when_simple = round(c(0.1289111, 0.5419274, 0.3291615, 0.33625, 0.51625, 0.14750), digits = 3) * 100)


# "#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"
simple_df %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C")) + 
    facet_wrap(~factor(simple_complex, levels = c("simple", "complex")))



################## base R pie ####################################
# when_obtain_simple_complex <- c("2 days or more",
#                         "24h or less",
#                         "Same day")
# 
# when_simple <- round(c(0.1289111, 0.5419274, 0.3291615), digits = 2) * 100
# when_complex <- round(c(0.33625, 0.51625, 0.14750), digits = 2) * 100
# 
# cols = brewer.pal(n = length(when_obtain_simple_complex), name = 'Set1')
# par(mfrow = c(1, 2))
# 
# # prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for simple procedures, low risk patients)."))
# pie(when_simple, 
#     labels = paste0(when_simple, "%"),
#     clockwise = TRUE,
#     col = cols,
#     cex.main=3, 
#     cex = 2.5,
#     main = "simple procedures",
#     radius = 1.2,
#     border = "white")
# 
# legend("bottom", 
#        legend = when_obtain_simple_complex,
#        fill = cols,
#        cex = 1.5, 
#        bty = "n",
#        border = "white",
#        inset = -.06)
# 
# # prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for complex procedures, higher risk patients)."))
# pie(when_complex,
#     labels = paste0(when_complex, "%"),
#     clockwise = TRUE,
#     cex.main=3, 
#     cex = 2.5,
#     col = cols,
#     main = "complex procedures",
#     radius = 1.2,
#     border = "white")
```
```{r PIE Do you know if it is legally allowed to obtain informed consent from the parent via Internet or telephone?}
prop.table(table(survey_data$"Do you know if it is legally allowed to obtain informed consent from the parent/caregiver via Internet or telephone?"))

online_legal_ped_answers <- data.frame(answer = c("Different", "Yes", "No"),
                                       counts = round(c(0.09813084, 0.22897196, 0.67289720), 3) * 100)

online_legal_ped_answers %>% 
    ggplot(aes(x="", y=counts, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(counts, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm')) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))

# pie(online_legal_ped, 
#     labels = paste0(online_legal_ped, "%"),
#     clockwise = TRUE,
#     col = cols,
#     cex.main=3, 
#     cex = 2.5,
#     radius = 0.8,
#     border = "white")
# 
# legend("bottomleft", 
#        legend = online_legal_ped_answers,
#        fill = cols,
#        cex = 1.6, 
#        bty = "n",
#        border = "white",
#        inset = -.06)
```
```{r MAP Do you know if it is legally allowed to obtain informed consent from the parent via Internet or telephone?}
# counts of responses in different countries
only_counts_responses <- survey_fragments %>% 
    dplyr::filter(country != "Other") %>% 
    count(country) %>% 
    select(n)

# getting the countries in R
mapdata <- map_data("world")

# 
map_dataframe <- survey_fragments %>% 
    dplyr::filter(country != "Other") %>% 
    select(country, parents.legal.online) %>% 
    group_by(country) %>% 
    mutate(parents.legal.online = ifelse(parents.legal.online == "Yes", 1, 0)) %>% 
    summarise(mean_legal = (mean(parents.legal.online, na.rm = TRUE)) *100 ) %>% 
    bind_cols(only_counts_responses) %>%
    dplyr::filter(n > 15) %>% 
    arrange(desc(n))

# changing column names, so mapdata and map_dataframe can be combined
colnames(map_dataframe) <- c("region", "mean_legal", "n")

# changing UK name so in can fit to mapdata
map_dataframe$region[map_dataframe$region == "United Kingdom (UK)"] <- "UK" 

#combining both dataframes
map_data <- left_join(mapdata, map_dataframe, by = "region")

# filtering NA and all the countries not included in the ESAIC survey
map_data %>% 
    dplyr::filter(!is.na(mean_legal)) %>% 
    ggplot(aes(x = long, 
               y = lat, 
               group = group)) +
    geom_polygon(aes(fill = mean_legal), 
                 color = "black") +
    scale_fill_gradient(name = "% Online consent is legal") +
    theme(axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.title.y = element_blank(),
          axis.title.x=element_blank(),
          legend.text = element_text(size = 20),
          legend.title = element_text(size = 25),
          rect = element_blank())

# Countries where online consent was stated to be legal
map_dataframe %>% 
    mutate(region = fct_reorder(as.factor(region), mean_legal)) %>% 
    ggplot(aes(x = region, y = mean_legal)) +
    geom_col() +
    labs(title = "Proportion ") +
    coord_flip()
```
```{r PIE Do you need to obtain written Informed consent for elective surgery from both parents or just from one?}
prop.table(table(survey_data$"Do you need to obtain written Informed consent for elective surgery due to legal requirements from both parents or just from one (simple procedures, low risk patients)?"))
prop.table(table(survey_data$"Do you need to obtain written Informed consent for elective surgery due to legal requirements from both parents or just from one (complex procedures, higher risk patients)?"))

consent_parents_simple_answers <- c("Both parents",
                            "Different",
                            "One, who is present")

cols = brewer.pal(n = length(consent_parents_simple_answers), name = 'Set1')
par(mfrow = c(1, 2))


consent_parents_simple <- round(c(0.14219474, 0.08191654, 0.77588872), digits = 2) * 100

pie(consent_parents_simple, 
    labels = paste0(consent_parents_simple, "%"),
    clockwise = TRUE,
    col = cols,
    cex.main=3, 
    cex = 2.5,
    main = "simple procedures",
    radius = 1.1,
    border = "white")

legend("bottom", 
       legend = consent_parents_simple_answers,
       fill = cols,
       cex = 1.7, 
       bty = "n",
       border = "white",
       inset = -.06)


consent_parents_complex <- round(c(0.2569231, 0.1046154, 0.6384615), digits = 2) * 100

pie(consent_parents_complex,
    labels = paste0(consent_parents_complex, "%"),
    clockwise = TRUE,
    cex.main=3, 
    cex = 2.5,
    col = cols,
    main = "complex procedures",
    radius = 1.1,
    border = "white")
```
```{r BARCHART ID dilemma}
table(survey_data$"Do you think it is necessary to verify the identity of the parent/guardian  (i.e. ID card)")
table(survey_data$"In case of personal presence of the parent/caregiver do you routinely check the identity or legal responsibility of the parent/caregiver (i.e. ID card)")

id_dilemma_tbl <- data.frame(Values = c(49, 234, 362, 29, 423, 193),
                             Answer = rep(c("Different", "No", "Yes"), 2),
                             # prevent geom_col to order bars alphabetically
                             dilemma = factor(c(rep("ID should be controlled", 3), rep("Actually controlled", 3)),
                                              levels = c("ID should be controlled", "Actually controlled")),
                             # percents for labeling the bars
                             prop_values = round((c(0.07596899, 0.36279070, 0.56124031, 0.04496124, 0.65581395, 0.29922481) * 100), 1))

id_dilemma_tbl %>%
    ggplot(aes(x = dilemma, y = Values, fill = Answer), position = "fill") +
    geom_col(colour="white") +
    scale_fill_brewer(palette = "Set1") + 
    theme(axis.text.x = element_text(size = 30),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          rect = element_blank(),
          legend.text = element_text(size=30),
          legend.title = element_blank(),
          legend.position = "left") + 
    geom_text(aes(label = paste0(prop_values, " %"), 
                  y = Values), 
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    scale_x_discrete(position = "top") 
```
```{r Plot ...: What are your major concerns about online or telephone interviews?}
reasons_against <- survey_fragments %>% 
    select(c("lack of contact", 
             "impossible to observe behavior", 
             "no relation", 
            "no confidence",
            "legal requirenments",
            "unsure if illigal")) %>%
    apply(MARGIN = 2, table) %>% 
    as_tibble()

colnames(reasons_against) <- c("Lack of contact", 
                               "Can't observe behavior", 
                               "No relationship",
                               "No confidence", 
                               "Legal requirenments", 
                               "Unsure if illigal")
# absolute numbers
reasons_against[2,]

# proportions 
prop_conserns <- gather(prop.table(reasons_against[2,]) * 100)  

prop_conserns %>% 
    mutate(key = fct_reorder(as.factor(key), -value)) %>% 
    ggplot(aes(x = key, y = value, fill = key)) +
        geom_col() +
        theme(axis.text.x = element_text(size = 15),
              axis.text.y = element_text(size = 30),
              axis.ticks = element_blank(),
              axis.title.y = element_blank(),
              axis.title.x = element_blank(),
              rect = element_blank(),
              legend.position = "none") + 
        scale_y_continuous(labels = function(x) paste0(x, "%"))
        theme(legend.position = "None") +
        scale_fill_brewer(palette = "Set1") +
        labs(x = "",
             y = "Responses") +
        coord_flip()
```
```{r Plot ...: What could be a major advantage of online/telephone interviews?}
reasons_for <- survey_fragments %>% 
    select(c("Less stressful",                  
             "Less waiting",                    
             "Standardized questionaires",      
             "More efficient than face-to-face")) %>%
    apply(MARGIN = 2, table) %>% 
    as_tibble()

# absolute numbers
reasons_for[2,]
# proportions 
prop_for <- gather(prop.table(reasons_for[2,]) * 100)

prop_for %>% 
    mutate(key = fct_reorder(as.factor(key), -value)) %>% 
    ggplot(aes(x = key, y = value, fill = key)) +
        geom_col() +
        theme(axis.text.x = element_text(size = 15),
              axis.text.y = element_text(size = 30),
              axis.ticks = element_blank(),
              axis.title.y = element_blank(),
              axis.title.x = element_blank(),
              rect = element_blank(),
              legend.position = "none") + 
        scale_y_continuous(labels = function(x) paste0(x, "%"))
        theme(legend.position = "None") +
        scale_fill_brewer(palette = "Set1") +
        labs(x = "",
             y = "Responses") +
        coord_flip()
```


```{r Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?}
# prop.table(table(survey_data$"Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?"))
pandemic_adjustments_values = round(c(0.2518703, 0.5610973, 0.1870324), 2) * 100

pie(pandemic_adjustments_values, 
    labels = paste0(pandemic_adjustments_values, "%"),
    clockwise = TRUE,
    col = cols,
    cex.main=3, 
    cex = 2.5,
    radius = 0.8,
    border = "white")


legend("bottom", 
       legend = pandemic_adnustments,
       fill = cols,
       cex = 1.5, 
       bty = "n",
       border = "white",
       horiz = TRUE,
       y = 2)

PieChart(pandemic_adjustments_values, hole = 0, values = "%", data = pandemic_adjustments_values, fill = 1:4, main = "")

```
```{r How would you prefer to do the anaesthesiological preoperative evaluation in the future?}
# prop.table(table(survey_data$"How would you prefer to do the anaesthesiological preoperative evaluation in the future?"))

# cols = brewer.pal(n = length(when_obtain_simple_complex), name = 'Set2')
colors = c("red", "yellow", "green", "violet")

future_consent <- c("In person",
                    "Online via patient´s self assessment",
                    "Online via videoconference",
                    "Via telefone")

future_consent_value =  round(c(0.77910053, 0.07539683, 0.11640212, 0.02910053), 2) * 100

pie(future_consent_value, 
    labels = paste0(future_consent_value, "%"),
    clockwise = TRUE,
    col = colors,
    cex.main=3, 
    cex = 2.5,
    radius = 0.8,
    border = "white")

legend("bottom", 
       legend = future_consent,
       fill = colors,
       cex = 1.5, 
       bty = "n",
       border = "white",
       inset = -.06)
```
```{r Technical implementation}
prop.table(table(survey_data$"Is it possible to obtain informed consent online via internet, in your routine setting?"))

colors = c("red", "yellow", "blue")
technical_possible <- c("Different", "No", "Yes")
technical_possible_values <- round(c(0.06647399, 0.70231214, 0.23121387), 2) * 100


pie(technical_possible_values, 
    labels = paste0(technical_possible_values, "%"),
    clockwise = TRUE,
    col = colors,
    cex.main=3, 
    cex = 2.5,
    radius = 0.8,
    border = "white")

legend("bottomleft", 
       legend = technical_possible,
       fill = colors,
       cex = 1.5, 
       bty = "n",
       border = "white",
       inset = -.06)
```






```{r Thinking of Re-Do / repeated anaesthesia assuming the patient is well informed. Would an online/telephone informed consent then be allowed for elective surgery due to legal requirements in your country?}

prop.table(table(survey_data$`When ensuring a certain guideline, which may include i.e. specific appointment (time and date) for the interview, secure data protected online service, asking if there is a relaxed environment without distraction, parents’ explicit agreement in online or telephone interview. Would this be an alternative to personal face-to-face meetings?`))


```

```{r Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)"}
### online legal simple vs complex
online_eccordance_simple <- c("I don't know", 
                              "No", 
                              "Yes")
cols = brewer.pal(n = length(online_eccordance_simple), name = 'Set3')
par(mfrow = c(1, 2))

# prop.table(table(survey_data$"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)"))


online_legal_simple <- round(c(0.3553616, 0.3715711, 0.2730673), 2) * 100
pie(online_legal_simple,
    labels = paste0(online_legal_simple, "%"), 
    clockwise = TRUE,
    cex = 1.5,
    col = cols,
    main = "simple procedures")
legend("bottom", 
       legend = online_eccordance_simple,
       fill = cols)
```

```{r countries for later}
countries <-
    c(
        "Austria",
        "Belgium",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Ireland",
        "Italy",
        "Latvia",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Netherlands",
        "Poland",
        "Portugal",
        "Romania",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "UK",
        "Turkey"
    )
```
```{r All questions separated by LimeSurvey}

"Gender"
"What is your age?"
"Profession"
"Your expert level"
"Years of experience"
"Country where you work?"

"Who in general obtains the informed consent prior to anaesthesia?"

"[ASA-Class] Which of the following Scores do you routinely use in preoperative evaluation?"
"[Apfel-Score] Which of the following Scores do you routinely use in preoperative evaluation?"
"[NYHA-Score] Which of the following Scores do you routinely use in preoperative evaluation?"
"[ARISCAT-Score] Which of the following Scores do you routinely use in preoperative evaluation?" 
"[rCRI] Which of the following Scores do you routinely use in preoperative evaluation?"
"[POSPOM] Which of the following Scores do you routinely use in preoperative evaluation?" 
"[Other] Which of the following Scores do you routinely use in preoperative evaluation?" 
"How would you prefer to do the anaesthesiological preoperative evaluation in the future?" 
"[Other] How would you prefer to do the anaesthesiological preoperative evaluation in the future?"
"When do you need to obtain Informed consent for elective surgery based on legal requirements (for complex procedures, higher risk patients)."
"When do you need to obtain Informed consent for elective surgery based on legal requirements (for simple procedures, low risk patients)."
"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for complex procedures, higher risk patients)"
"[Comment] Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for complex procedures, higher risk patients)"
"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)"
"[Comment] Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)"
"Thinking of Re-Do / repeated anaesthesia assuming the patient is well informed. Would an online/telephone informed consent then be allowed for elective surgery due to legal requirements in your country?"
"Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?"
"Is it possible to obtain informed consent online via internet, in your routine setting?"
"[Comment] Is it possible to obtain informed consent online via internet, in your routine setting?"
"Is it possible to obtain informed consent online via telefone, in your routine setting?"
"[Comment] Is it possible to obtain informed consent online via telefone, in your routine setting?"
"Do you know if it is legally allowed to obtain informed consent via Internet or telephone (for simple procedures, low risk patients) in your country?"
"[Comment] Do you know if it is legally allowed to obtain informed consent via Internet or telephone (for simple procedures, low risk patients) in your country?" 
"When ensuring a certain guideline, which may include i.e. specific appointment (time and date) for the interview, secure data protected online service, asking if there is a relaxed environment without distraction, parents’ explicit agreement in online or telephone interview. Would this be an alternative to personal face-to-face meetings?"
"[Comment] When ensuring a certain guideline, which may include i.e. specific appointment (time and date) for the interview, secure data protected online service, asking if there is a relaxed environment without distraction, parents’ explicit agreement in online or telephone interview. Would this be an alternative to personal face-to-face meetings?"
"[Lack of personal contact] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[Patient´s behaviour is impossible to observe] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[Personal relation with the patient cannot be build] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[Confidence in anaesthesia cannot be achieved] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[Impossible to fulfil legal requirements] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[I am not sure if it might be illegal in my country] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[Impossible to gather for anamnestic information] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[Other] What are your major concerns about online or telephone interviews? (More than one answer is possible)"
"[If patients are from remote locations,  no travel or transportation is necessary] What could be a major advantage of online/telephone interviews? (More than one answer is possible)"
"[More relaxed for the patients] What could be a major advantage of online/telephone interviews? (More than one answer is possible)"
"[No waste of time waiting in the holding area] What could be a major advantage of online/telephone interviews? (More than one answer is possible)" 
"[Less anger/stress due to long waiting] What could be a major advantage of online/telephone interviews? (More than one answer is possible)"
"[With specific questions all information could be obtained] What could be a major advantage of online/telephone interviews? (More than one answer is possible)"
"[Together with special designed written information and professional pre-produced videos it might be more efficient than face-to-face meeting] What could be a major advantage of online/telephone interviews? (More than one answer is possible)"
"[Other] What could be a major advantage of online/telephone interviews? (More than one answer is possible)"
"Do you need to obtain written Informed consent for elective surgery due to legal requirements from both parents or just from one (complex procedures, higher risk patients)?"
"[Comment] Do you need to obtain written Informed consent for elective surgery due to legal requirements from both parents or just from one (complex procedures, higher risk patients)?"
"Do you need to obtain written Informed consent for elective surgery due to legal requirements from both parents or just from one (simple procedures, low risk patients)?"
"[Comment] Do you need to obtain written Informed consent for elective surgery due to legal requirements from both parents or just from one (simple procedures, low risk patients)?"
"[Age above ...] What requirements does a child have to fulfil to sign independently?"
"[Comment] [Age above ...] What requirements does a child have to fulfil to sign independently?"
"[Having the mental capacity to understand the consequences of its decision] What requirements does a child have to fulfil to sign independently?"
"[Comment] [Having the mental capacity to understand the consequences of its decision] What requirements does a child have to fulfil to sign independently?"
"[other ...] What requirements does a child have to fulfil to sign independently?"
"[Comment] [other ...] What requirements does a child have to fulfil to sign independently?"
"Do you know if it is legally allowed to obtain informed consent from the parent/caregiver via Internet or telephone?"
"[Comment] Do you know if it is legally allowed to obtain informed consent from the parent/caregiver via Internet or telephone?"
"In case of personal presence of the parent/caregiver do you routinely check the identity or legal responsibility of the parent/caregiver (i.e. ID card)"
"[Comment] In case of personal presence of the parent/caregiver do you routinely check the identity or legal responsibility of the parent/caregiver (i.e. ID card)"
"Do you think it is necessary to verify the identity of the parent/guardian  (i.e. ID card)"
"[Comment] Do you think it is necessary to verify the identity of the parent/guardian  (i.e. ID card)"

```


```{r pie experimentation}
simple_df <- data.frame(simple_complex = c(rep("simple", 3), rep("complex", 3)),
                        answer = rep(c("2 days or more", "24h or less", "Same day"), 2),
                        when_simple = round(c(0.1289111, 0.5419274, 0.3291615, 0.33625, 0.51625, 0.14750), digits = 3) * 100)


# "#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"
simple_df %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C")) + 
    facet_wrap(~factor(simple_complex, levels = c("simple", "complex")))
```

